### ISSUE TITLE
huddle-bot-yrf4w7/web Sourcecontrols BadRequest fail

### ISSUE THREAD

**Issue by pstork** [OfficeDev/Office-365-Huddle-Templates#3]
In the documentation it says if you get a BadRequest for the sourcecontrols step of the deployment to try again because it may happen 2 or 3 times.  I have tried redeploying 10 times now.  It always fails at this step saying:

 "Code": "BadRequest",
  "Message": "Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetRepository: Bad credentials\r\n  

Can anyone suggest how to troubleshoot this?

**Comment by pstork** [comment]
Never mind.  Evidently the 11th time is the charm.  Got it to deploy successfully.

**Comment by susrut** [comment]
Hello @pstork , If you don't mind can you please share the workaround resolution for the above issue. :)

**Comment by db9crt** [comment]
Could you let me know how u managed to resolve it
